### ISSUE TITLE
Unable to run after installation.

### ISSUE THREAD

**Issue by ZUIcat** [owebeeone/anchorscad-core#1]
I installed it via pip and tried the first command from the documentation, but it didn't work.

```bat
>python -m anchorscad.core --shape Box --write
runpy.py:126: RuntimeWarning: 'anchorscad.core' found in sys.modules after import of package 'anchorscad', but prior to execution of 'anchorscad.core'; this may result in unpredictable behaviour
Traceback (most recent call last):
  File "runpy.py", line 196, in _run_module_as_main
  File "runpy.py", line 86, in _run_code
  File "C:\Users\ZUIcat\Downloads\ss\python-3.10.11-embed\lib\site-packages\anchorscad\core.py", line 3312, in <module>
    anchorscad_main()
  File "C:\Users\ZUIcat\Downloads\ss\python-3.10.11-embed\lib\site-packages\anchorscad\core.py", line 3302, in anchorscad_main
    clr = ExampleCommandLineRenderer(sys.argv[1:], do_exit_on_completion)
  File "C:\Users\ZUIcat\Downloads\ss\python-3.10.11-embed\lib\site-packages\anchorscad\core.py", line 2896, in __init__
    self.parse()
  File "C:\Users\ZUIcat\Downloads\ss\python-3.10.11-embed\lib\site-packages\anchorscad\core.py", line 3070, in parse
    raise InvalidParametersException(f"Parameters provided were not parsed: {str(argv)}")
__main__.InvalidParametersException: Parameters provided were not parsed: ['--shape', 'Box']

>python -m pip show anchorscad.core
Name: anchorscad-core
Version: 0.2.3
Summary: A Python 3D modelling API for generating OpenSCAD source code. This library simplifies the creating of 3D models. This contains only the core API and some generic basic models.
Home-page: https://github.com/owebeeone/anchorscad-core
Author:
Author-email: Gianni Mariani <gianni@mariani.ws>
License:
Location: c:\users\zuicat\downloads\ss\python-3.10.11-embed\lib\site-packages
Requires: anchorscad-linear, anchorscad-test-tools, anchorscad-utils, dataclasses-json, datatrees, debugpy, dill, frozendict, graphviz, lxml, matplotlib, numpy, numpy-stl, pillow, pythonopenscad, sortedcollections, sortedcontainers, svgelements, svgpathtools, to-3mf, xdatatrees
Required-by:
```

**Comment by ZUIcat** [comment]
But if add ` --material default` after it, it will run.

**Comment by owebeeone** [comment]
This invocation runs the module (which calls anchorscad_main())
```
python -m anchorscad.core
```
If I run that with --help I get:
```
 python -m anchorscad.core --help                   
<frozen runpy>:128: RuntimeWarning: 'anchorscad.core' found in sys.modules after import of package 'anchorscad', but prior to execution of 'anchorscad.core'; this may result in unpredictable behaviour
usage: core.py [-h] [--no-write] [--write] [--write-parts] [--no-write-parts] [--graph_write] [--no-graph_write] [--svg_write] [--no-svg_write] [--stl_mesh_write] [--no-stl_mesh_write]
               [--out_file_name OUT_FILE_NAME] [--part_out_file_name PART_OUT_FILE_NAME] [--stl_mesh_out_file_name STL_MESH_OUT_FILE_NAME] [--graph_file_name GRAPH_FILE_NAME] [--no_write_path_files]
               [--write_path_files] [--no_write_injection_files] [--write_injection_files] [--paths_file_name PATHS_FILE_NAME] [--injected_fields_file_name INJECTED_FIELDS_FILE_NAME] [--level LEVEL]
               [--class_name [CLASS_NAME ...]] [--warn_deprecated_anchors_use] [--no_warn_deprecated_anchors_use] [--module MODULE] [--list_shapes]

    Renders Anchorscad examples their respective scad files.
...
```
Note there is no "--shape" parameter - the equivalent is --class_name like:
```
python -m anchorscad.core --class_name Box --write
```

That works fine.

I think you may have meant to run ad_viewer:

```
python -m anchorscad.ad_viewer --shape Box
```
`python -m anchorscad.ad_viewer --help` shows you have 

```
usage: ad_viewer.py [-h] [--output-base OUTPUT_BASE] [--solids] [--no-solids] [--view] [--no-view] [--stl] [--no-stl] [--png] [--no-png] [--scad] [--no-scad] [--wireframe] [--no-wireframe]
                    [--backface-culling] [--no-backface-culling] [--bounding-box-mode] [--no-bounding-box-mode] [--zbuffer-occlusion] [--no-zbuffer-occlusion] [--coalesce] [--no-coalesce] [--width WIDTH]       
                    [--height HEIGHT] [--title TITLE] [--projection {perspective,orthographic}] [--bg-color BG_COLOR] [--example EXAMPLE] [--module MODULE] [--shape SHAPE] [--part PART] [--material MATERIAL]   

View or export PythonOpenSCAD objects.
... <snip> ...
  --example EXAMPLE     The example name to use for the shape.
  --module MODULE       The module name to import the shape from.
  --shape SHAPE         The shape class name to use.
  --part PART           The part name to use. If not provided, the part name will be the combined file containing all parts.
  --material MATERIAL   The material name to use. If not provided, all materials will be used.
...
```
`--module` defaults to "`anchorscad`", that's why `--shape Box` works.

It's not a bug though I'm happy for suggestions. Maybe more example command lines.

**Comment by ZUIcat** [comment]
~~However, these command lines were copied from the README, not organized by myself. If there are any issues, they should be corrected in the documentation.~~
Sorry, I just checked the README again—the command I initially used isn’t actually there. That’s strange… Since I’m new to this library, I definitely copied and pasted it rather than typing it myself. I wonder where it came from...

**Comment by ZUIcat** [comment]
> ~However, these command lines were copied from the README, not organized by myself. If there are any issues, they should be corrected in the documentation.~ Sorry, I just checked the README again—the command I initially used isn’t actually there. That’s strange… Since I’m new to this library, I definitely copied and pasted it rather than typing it myself. I wonder where it came from...

Ah, found it here: <https://github.com/owebeeone/anchorscad-core/blob/main/docs/InstallingAnchorSCAD.md#testing-the-installation>. Looks like it needs to be corrected.

**Comment by ZUIcat** [comment]
Also, I've tested the command and they don't seem to work either:

```bat
>python -m anchorscad.ad_viewer --shape Box
Error rendering object 'item_0': get_fragments_from_fn_fa_fs() missing 3 required positional arguments: 'fn', 'fa', and 'fs'
Traceback (most recent call last):
  File "runpy.py", line 196, in _run_module_as_main
  File "runpy.py", line 86, in _run_code
  File "C:\Users\ZUIcat\Downloads\ss\python-3.10.11-embed\lib\site-packages\anchorscad\ad_viewer.py", line 171, in <module>
    main()
  File "C:\Users\ZUIcat\Downloads\ss\python-3.10.11-embed\lib\site-packages\anchorscad\ad_viewer.py", line 108, in main
    runner.run()
  File "C:\Users\ZUIcat\Downloads\ss\python-3.10.11-embed\lib\site-packages\pythonopenscad\posc_main.py", line 231, in run
    viewer_models.extend(model.get_viewer_models(include_shells=not self.args.solids))
  File "C:\Users\ZUIcat\Downloads\ss\python-3.10.11-embed\lib\site-packages\pythonopenscad\posc_main.py", line 62, in get_viewer_models
    manifold = self.get_solid_manifold()
  File "C:\Users\ZUIcat\Downloads\ss\python-3.10.11-embed\lib\site-packages\pythonopenscad\posc_main.py", line 50, in get_solid_manifold
    context = self.render()
  File "C:\Users\ZUIcat\Downloads\ss\python-3.10.11-embed\lib\site-packages\pythonopenscad\posc_main.py", line 42, in render
    self._render_context = posc_obj.renderObj(M3dRenderer())
  File "C:\Users\ZUIcat\Downloads\ss\python-3.10.11-embed\lib\site-packages\pythonopenscad\base.py", line 1784, in renderObj
    return renderer.union(self)
  File "C:\Users\ZUIcat\Downloads\ss\python-3.10.11-embed\lib\site-packages\pythonopenscad\m3dapi.py", line 1055, in union
    return RenderStateCheckManifold.check(self, posc_obj, lambda ops: self._union(ops))
  File "C:\Users\ZUIcat\Downloads\ss\python-3.10.11-embed\lib\site-packages\pythonopenscad\m3dapi.py", line 701, in check
    args = (renderer.renderChildren(posc_obj),)
  File "C:\Users\ZUIcat\Downloads\ss\python-3.10.11-embed\lib\site-packages\pythonopenscad\m3dapi.py", line 769, in renderChildren
    child_ctxt = child.renderObj(self)
  File "C:\Users\ZUIcat\Downloads\ss\python-3.10.11-embed\lib\site-packages\pythonopenscad\base.py", line 1828, in renderObj
    return renderer.union(self)
  File "C:\Users\ZUIcat\Downloads\ss\python-3.10.11-embed\lib\site-packages\pythonopenscad\m3dapi.py", line 1055, in union
    return RenderStateCheckManifold.check(self, posc_obj, lambda ops: self._union(ops))
  File "C:\Users\ZUIcat\Downloads\ss\python-3.10.11-embed\lib\site-packages\pythonopenscad\m3dapi.py", line 701, in check
    args = (renderer.renderChildren(posc_obj),)
  File "C:\Users\ZUIcat\Downloads\ss\python-3.10.11-embed\lib\site-packages\pythonopenscad\m3dapi.py", line 769, in renderChildren
    child_ctxt = child.renderObj(self)
  File "C:\Users\ZUIcat\Downloads\ss\python-3.10.11-embed\lib\site-packages\pythonopenscad\base.py", line 1773, in renderObj
    return renderer.union(self)
  File "C:\Users\ZUIcat\Downloads\ss\python-3.10.11-embed\lib\site-packages\pythonopenscad\m3dapi.py", line 1055, in union
    return RenderStateCheckManifold.check(self, posc_obj, lambda ops: self._union(ops))
  File "C:\Users\ZUIcat\Downloads\ss\python-3.10.11-embed\lib\site-packages\pythonopenscad\m3dapi.py", line 701, in check
    args = (renderer.renderChildren(posc_obj),)
  File "C:\Users\ZUIcat\Downloads\ss\python-3.10.11-embed\lib\site-packages\pythonopenscad\m3dapi.py", line 769, in renderChildren
    child_ctxt = child.renderObj(self)
  File "C:\Users\ZUIcat\Downloads\ss\python-3.10.11-embed\lib\site-packages\pythonopenscad\base.py", line 1385, in renderObj
    return renderer.multmatrix(self, self.m)
  File "C:\Users\ZUIcat\Downloads\ss\python-3.10.11-embed\lib\site-packages\pythonopenscad\m3dapi.py", line 1548, in multmatrix
    return RenderStateCheckManifold.check(self, posc_obj, lambda ops: self._multmatrix(ops, m))
  File "C:\Users\ZUIcat\Downloads\ss\python-3.10.11-embed\lib\site-packages\pythonopenscad\m3dapi.py", line 701, in check
    args = (renderer.renderChildren(posc_obj),)
  File "C:\Users\ZUIcat\Downloads\ss\python-3.10.11-embed\lib\site-packages\pythonopenscad\m3dapi.py", line 769, in renderChildren
    child_ctxt = child.renderObj(self)
  File "C:\Users\ZUIcat\Downloads\ss\python-3.10.11-embed\lib\site-packages\pythonopenscad\base.py", line 1773, in renderObj
    return renderer.union(self)
  File "C:\Users\ZUIcat\Downloads\ss\python-3.10.11-embed\lib\site-packages\pythonopenscad\m3dapi.py", line 1055, in union
    return RenderStateCheckManifold.check(self, posc_obj, lambda ops: self._union(ops))
  File "C:\Users\ZUIcat\Downloads\ss\python-3.10.11-embed\lib\site-packages\pythonopenscad\m3dapi.py", line 701, in check
    args = (renderer.renderChildren(posc_obj),)
  File "C:\Users\ZUIcat\Downloads\ss\python-3.10.11-embed\lib\site-packages\pythonopenscad\m3dapi.py", line 769, in renderChildren
    child_ctxt = child.renderObj(self)
  File "C:\Users\ZUIcat\Downloads\ss\python-3.10.11-embed\lib\site-packages\pythonopenscad\base.py", line 1773, in renderObj
    return renderer.union(self)
  File "C:\Users\ZUIcat\Downloads\ss\python-3.10.11-embed\lib\site-packages\pythonopenscad\m3dapi.py", line 1055, in union
    return RenderStateCheckManifold.check(self, posc_obj, lambda ops: self._union(ops))
  File "C:\Users\ZUIcat\Downloads\ss\python-3.10.11-embed\lib\site-packages\pythonopenscad\m3dapi.py", line 701, in check
    args = (renderer.renderChildren(posc_obj),)
  File "C:\Users\ZUIcat\Downloads\ss\python-3.10.11-embed\lib\site-packages\pythonopenscad\m3dapi.py", line 769, in renderChildren
    child_ctxt = child.renderObj(self)
  File "C:\Users\ZUIcat\Downloads\ss\python-3.10.11-embed\lib\site-packages\pythonopenscad\base.py", line 1385, in renderObj
    return renderer.multmatrix(self, self.m)
  File "C:\Users\ZUIcat\Downloads\ss\python-3.10.11-embed\lib\site-packages\pythonopenscad\m3dapi.py", line 1548, in multmatrix
    return RenderStateCheckManifold.check(self, posc_obj, lambda ops: self._multmatrix(ops, m))
  File "C:\Users\ZUIcat\Downloads\ss\python-3.10.11-embed\lib\site-packages\pythonopenscad\m3dapi.py", line 701, in check
    args = (renderer.renderChildren(posc_obj),)
  File "C:\Users\ZUIcat\Downloads\ss\python-3.10.11-embed\lib\site-packages\pythonopenscad\m3dapi.py", line 769, in renderChildren
    child_ctxt = child.renderObj(self)
  File "C:\Users\ZUIcat\Downloads\ss\python-3.10.11-embed\lib\site-packages\pythonopenscad\base.py", line 1409, in renderObj
    return renderer.color(self, self.c, self.alpha)
  File "C:\Users\ZUIcat\Downloads\ss\python-3.10.11-embed\lib\site-packages\pythonopenscad\m3dapi.py", line 1506, in color
    return RenderStateCheckManifold.check(
  File "C:\Users\ZUIcat\Downloads\ss\python-3.10.11-embed\lib\site-packages\pythonopenscad\m3dapi.py", line 701, in check
    args = (renderer.renderChildren(posc_obj),)
  File "C:\Users\ZUIcat\Downloads\ss\python-3.10.11-embed\lib\site-packages\pythonopenscad\m3dapi.py", line 769, in renderChildren
    child_ctxt = child.renderObj(self)
  File "C:\Users\ZUIcat\Downloads\ss\python-3.10.11-embed\lib\site-packages\pythonopenscad\base.py", line 1773, in renderObj
    return renderer.union(self)
  File "C:\Users\ZUIcat\Downloads\ss\python-3.10.11-embed\lib\site-packages\pythonopenscad\m3dapi.py", line 1055, in union
    return RenderStateCheckManifold.check(self, posc_obj, lambda ops: self._union(ops))
  File "C:\Users\ZUIcat\Downloads\ss\python-3.10.11-embed\lib\site-packages\pythonopenscad\m3dapi.py", line 701, in check
    args = (renderer.renderChildren(posc_obj),)
  File "C:\Users\ZUIcat\Downloads\ss\python-3.10.11-embed\lib\site-packages\pythonopenscad\m3dapi.py", line 769, in renderChildren
    child_ctxt = child.renderObj(self)
  File "C:\Users\ZUIcat\Downloads\ss\python-3.10.11-embed\lib\site-packages\pythonopenscad\base.py", line 1385, in renderObj
    return renderer.multmatrix(self, self.m)
  File "C:\Users\ZUIcat\Downloads\ss\python-3.10.11-embed\lib\site-packages\pythonopenscad\m3dapi.py", line 1548, in multmatrix
    return RenderStateCheckManifold.check(self, posc_obj, lambda ops: self._multmatrix(ops, m))
  File "C:\Users\ZUIcat\Downloads\ss\python-3.10.11-embed\lib\site-packages\pythonopenscad\m3dapi.py", line 701, in check
    args = (renderer.renderChildren(posc_obj),)
  File "C:\Users\ZUIcat\Downloads\ss\python-3.10.11-embed\lib\site-packages\pythonopenscad\m3dapi.py", line 769, in renderChildren
    child_ctxt = child.renderObj(self)
  File "C:\Users\ZUIcat\Downloads\ss\python-3.10.11-embed\lib\site-packages\pythonopenscad\base.py", line 1773, in renderObj
    return renderer.union(self)
  File "C:\Users\ZUIcat\Downloads\ss\python-3.10.11-embed\lib\site-packages\pythonopenscad\m3dapi.py", line 1055, in union
    return RenderStateCheckManifold.check(self, posc_obj, lambda ops: self._union(ops))
  File "C:\Users\ZUIcat\Downloads\ss\python-3.10.11-embed\lib\site-packages\pythonopenscad\m3dapi.py", line 701, in check
    args = (renderer.renderChildren(posc_obj),)
  File "C:\Users\ZUIcat\Downloads\ss\python-3.10.11-embed\lib\site-packages\pythonopenscad\m3dapi.py", line 769, in renderChildren
    child_ctxt = child.renderObj(self)
  File "C:\Users\ZUIcat\Downloads\ss\python-3.10.11-embed\lib\site-packages\pythonopenscad\base.py", line 1221, in renderObj
    get_fragments_from_fn_fa_fs(self.get_r1(), **self.get_fn_fa_fs_args()),
TypeError: get_fragments_from_fn_fa_fs() missing 3 required positional arguments: 'fn', 'fa', and 'fs'
```

**Comment by DeepReef11** [comment]
I also get that error while trying the example. Adding --material default did not solve it for me. Using Python 3.13.5 in venv.

**Comment by DeepReef11** [comment]
Should I open a new issue? I cannot reopen this one

I've tried other commands in this issue, this one seems to work fine:
python -m anchorscad.core --class_name Box --write

So I guess the readme needs an update?

**Comment by owebeeone** [comment]
Those line numbers correspond to an earlier version of PythonOpenScad. This
issue has been fixed.

You're running an earlier version of PythonOpenScad that has this bug. Do a
pip --upgrade pythonopenscad anchorscad-core.

See:the fix:
https://github.com/owebeeone/pythonopenscad/commit/038e578cbbfd19d0bbe86224fbc32b35fe74acde

**Comment by DeepReef11** [comment]
I have installed from main branch. I suppose I should have switched to stable? I've just installed from pip instead, now it seems to work
